primary:
keys:
  Shot:
      type: str
  Task:
    type: str
  Test:
    type: str

paths:
  main: 'D:\Desk\python\sgtk'
  root: ""
  desk: '@root\@dir'
  shot_root: '@main\shots'
  shot_task: '@shot_root\aaaa\{Test}'
  test_templates: '@shot_task\{Shot}\{Task}\cmp'
