keys:
  Root:
    type: str
  Shot:
    type: str
  Task:
    type: str
  dir:
    type: str
  version:
    type: int
    format_spec: "03"

paths:
  rootDir: "D:\\Desk\\python\\Tank\\tests\\project"
  desk: '@rootDir\\{dir}'
  test: '@desk\\{Shot}\\{Task}'
  nuke: '@test\\nuke\\{Shot}-{Task}-base-v{version}.nk'
  test_diff: '@desk\\nuke\\{Shot}-{Task}-base-v{version}.nk'
